# Generated by Django 4.2.2 on 2023-07-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate_link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_link',
            field=models.URLField(),
        ),
        migrations.DeleteModel(
            name='SocialMedia',
        ),
    ]
