# Generated by Django 4.2.2 on 2023-07-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_alter_certificate_user_alter_education_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='user',
        ),
        migrations.RemoveField(
            model_name='education',
            name='user',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='user',
        ),
        migrations.RemoveField(
            model_name='link',
            name='user',
        ),
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
        migrations.AddField(
            model_name='customuser',
            name='certificates',
            field=models.ManyToManyField(blank=True, related_name='customuser_set', to='resume.certificate'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='educations',
            field=models.ManyToManyField(blank=True, related_name='customuser_set', to='resume.education'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='experiencies',
            field=models.ManyToManyField(blank=True, related_name='customuser_set', to='resume.experience'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='links',
            field=models.ManyToManyField(blank=True, related_name='customuser_set', to='resume.link'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='customuser_set', to='resume.project'),
        ),
    ]
