# Generated by Django 4.2.2 on 2023-07-31 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_remove_customuser_certificates_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='user',
        ),
    ]
