# Generated by Django 4.2.2 on 2023-08-01 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_certificate_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='user',
        ),
    ]
