# Generated by Django 4.2.2 on 2023-08-02 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_certificate_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='sub_description',
        ),
    ]
