# Generated by Django 4.2.2 on 2023-08-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0012_remove_project_end_date_remove_project_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='topics',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
