# Generated by Django 4.2.2 on 2023-08-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0013_project_language_project_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='topics',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
