# Generated by Django 4.2.2 on 2023-08-04 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0014_alter_project_topics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='description',
        ),
    ]
