# Generated by Django 4.2.2 on 2023-08-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0015_remove_experience_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='updateDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
