# Generated by Django 4.2.2 on 2023-08-06 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0016_project_updatedate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='updateDate',
            new_name='update_date',
        ),
    ]
